### ISSUE TITLE
always show "Internal compile error. ...."

### ISSUE THREAD

**Issue by kumbayaco** [SaladLab/Unity3D.IncrementalCompiler#5]
My unity version is 4.6.9p1, when i modify any code, the console always show errors below.

Internal compiler error. See the console log for more information. output was:Internal error: System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: preprocessorSymbols (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.ArgumentException: preprocessorSymbols
at Microsoft.CodeAnalysis.CSharp.CSharpParseOptions..ctor(LanguageVersion languageVersion, DocumentationMode documentationMode, SourceCodeKind kind, IEnumerable`1 preprocessorSymbols)
at IncrementalCompiler.Compiler.BuildFull(CompileOptions options)
at IncrementalCompiler.Compiler.Build(CompileOptions options)
at IncrementalCompiler.CompilerService.Build(String projectPath, CompileOptions options)
at SyncInvokeBuild(Object , Object[] , Object[] )
at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc)
at System...).

**Comment by veblush** [comment]
Thanks for report. It has been a long time since I have run Unity 4. I'll take a look at this problem.

**Comment by veblush** [comment]
Ok. I fix it and make [new release](https://github.com/SaladLab/Unity3D.IncrementalCompiler/releases/tag/v1.2.3). Please check it out.

Unity4 was passing an illegal preprocessor to a compiler which was `ENABLE_NEW_HIERARCHY ` (it has a trailing space) New compiler trims it before passing it to compiler.

**Comment by kumbayaco** [comment]
Thanks for your reply. But still have another error.

`Internal compiler error. See the console log for more information. output was:Internal error: System.ServiceModel.CommunicationException: The maximum message size quota for incoming messages (1048576) has been exceeded. To increase the quota, use the MaxReceivedMessageSize property on the appropriate binding element. ---> System.ServiceModel.QuotaExceededException: The maximum message size quota for incoming messages (1048576) has been exceeded. To increase the quota, use the MaxReceivedMessageSize property on the appropriate binding element.
--- End of inner exception stack trace ---
Server stack trace:
at System.ServiceModel.Channels.ClientDuplexConnectionReader.DecodeMessage(Byte[] buffer, Int32& offset, Int32& size, Boolean& isAtEOF, TimeSpan timeout)
at System.ServiceModel.Channels.SessionConnectionReader.DecodeMessage(TimeSpan timeout)
at System.ServiceModel.Channels.SessionConnectionReader.Receive(TimeSpan timeout)
at System.ServiceModel.Channels.SynchronizedMessageSource.Receive(TimeSpan timeout)
at System.ServiceModel.Channels.TransportDuplexSessionChannel.Receive(TimeSpan timeout)
at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceive(TimeSpan timeout, Message& message)
at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
Exception rethrown at [0]:
at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
at IncrementalCompiler.ICompilerService.Build(String projectPath, CompileOptions options)
at IncrementalCompiler.CompilerServiceClient.Request(Int32 parentProcessId, String currentPath, CompileOptions options)
at IncrementalCompiler.Program.RunAsClient(String[] args)`

btw, how can i turn off "/unsafe ", There is so many unsafe code in my 3rd library, I can't modify them at all.

Thanks.

**Comment by veblush** [comment]
Oh another bugs!

To fix those problems, WCF buffer size is increased and -unsafe options is turned on by default.
Please check out [new release](https://github.com/SaladLab/Unity3D.IncrementalCompiler/releases/tag/v1.2.3) which is replaced on same version.

**Comment by kumbayaco** [comment]
Thanks for quick reply!!

I tried. but some other error appeared. it seems like the mscrolib's problem. how can i solve this?

`error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.`

**Comment by veblush** [comment]
When I wrote small sample on Unity4, everything went well. So could you explain about your build environment? and please show me compiler logs on Assets/CompilerSetting dialog box.

If your build platform is Web Player (in Build Settings), it could be a reason that causes that problem. Web Player seems not compatible with Roslyn compiler.

**Comment by kumbayaco** [comment]
My platform is android. and os is Windows7 64,
The log file is so large that I can only post part of the log
`
********************************************************************************
*                           2016-06-01 09:30:10.050                            *
********************************************************************************
CSharpCompilerWrapper.exe version: 1.2.3.0
Platform: Windows
Target assembly: Assembly-CSharp.dll
Project directory: E:\root\MyProj\UnityProj
Unity 'Data' or 'Frameworks' directory: D:/Program Files (x86)/Unity4.6.9p1/Editor/Data
Compiler: Incremental C# Compiler 6.0

- Compilation -----------------------------------------------

Process: E:\root\MyProj\UnityProj\Compiler\IncrementalCompiler.exe
Arguments: -nostdlib+ -noconfig -r:"D:/Program Files (x86)/Unity4.6.9p1/Editor/Data\Mono/lib/mono/2.0/mscorlib.dll" -r:"D:/Program Files (x86)/Unity4.6.9p1/Editor/Data\Mono/lib/mono/2.0/System.dll" -r:"D:/Program Files (x86)/Unity4.6.9p1/Editor/Data\Mono/lib/mono/2.0/System.Core.dll" -r:"D:/Program Files (x86)/Unity4.6.9p1/Editor/Data\Mono/lib/mono/2.0/System.Xml.dll" @Temp/UnityTempFile-6018afb6ac67fea4fbce661a9d29d7f9
Exit code: 1
Elapsed time: 6.18 sec

- Compiler output (1 line):
0: Compile failed. (Duration=4.1900744sec)

- Compiler errors (11950 lines):
11520: E:\root\MyProj\UnityProj\Assets/ShareWithDS/Scripts/Trigger/EnemyPoint/EnemyPointGroupMsg.cs(62,35): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
11521: E:\root\MyProj\UnityProj\Assets/ShareWithDS/Scripts/Trigger/EnemyPoint/EnemyPointGroupMsg.cs(66,35): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
......
11835: E:\root\MyProj\UnityProj\Assets/ShareWithDS/Scripts/Weapon/Track/TrackFollow_MS20.cs(108,16): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
11836: E:\root\MyProj\UnityProj\Assets/ShareWithDS/Scripts/Weapon/BulletManager.cs(438,20): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
11837: E:\root\MyProj\UnityProj\Assets/ShareWithDS/Scripts/Weapon/Track/TrackParabolaPeak.cs(32,20): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.`

**Comment by veblush** [comment]
Hmm. It is getting tricky. I was delving into unity-mono compiler environment and found out that my compiler always use `.NET 2.0` (mscorlib 2.0.0.0) even if api compatibility level is set to `.NET 2.0 Subset` (mscorlib 2.0.5.0). In according to your compile log, compiler discovered `.NET 2.0 Subset` and tried to link it but failed.

So my additional question is what is your `Api compatibility level` of your project. If it is `.NET 2.0 Subset`, please change it to `.NET 2.0` and try it again.

**Comment by veblush** [comment]
I just released [1.2.4](https://github.com/SaladLab/Unity3D.IncrementalCompiler/releases/tag/v1.2.4) to handle `.NET 2.0 Subset` profile.
Please try new compiler with `.NET 2.0 Subset` build option.

**Comment by kumbayaco** [comment]
Thanks a lot, it works now!!

**Comment by veblush** [comment]
Great! Please enjoy it :smile:
